### PR TITLE
added default value

### PR DESCRIPTION
**Pull request by cmorgan-osi**

### CODE REVIEW

**Comment by ewillis-osi** [comment]
We just need to add MaxHistoryEventsPerSecond to the DataSource configuration

**Comment by bballentine123** [comment]
Do we also need to add DataCollectionMode to the DataSource configuration?

**Comment by TinaUll** [comment]
Hi @cmorgan-osi, @ewillis-osi, and @bballentine123 is this PR ready to be merged?

**Comment by cmorgan-osi** [comment]
@ewillis-osi @bballentine123 does this accurately summarize your suggestions?

**Review by bballentine123 — APPROVED** [review]
Looks good to me!

**Comment by ewillis-osi** [comment]
Looks good!

**Review by ewillis-osi — APPROVED** [review]

**Review by TinaUll — APPROVED** [review]

**Pull request merged**
